export default  {
    TWITTER: {domObj:"BLOCKQUOTE",compare:{attr:"class",value:"twitter-tweet"}, blockName:"twitter"},
    TWITTERVIDEO: {domObj:"BLOCKQUOTE",compare:{attr:"class",value:"twitter-video"}, blockName:"twitter"},
    INSTAGRAM: {domObj:"BLOCKQUOTE",compare:{attr:"class",value:"instagram-media"}, blockName:"instagram"},
    YOUTUBE: {domObj:"IFRAME",compare:{attr:"src",value:"youtube.com/embed"}, blockName:"youtube"},
    VINE: {domObj:"IFRAME",compare:{attr:"src",value:"vine.co"}, blockName:"vine"},
    FACEBOOK: {domObj:"IFRAME",compare:{attr:"src",value:"facebook.com/plugins"}, blockName:"facebook"},
    GOOGLEMAP: {domObj:"IFRAME",compare:{attr:"src",value:"google.com/maps"}, blockName:"googlemap"},
    SOUNDCLOUD: {domObj:"IFRAME",compare:{attr:"src",value:"w.soundcloud.com/player"}, blockName:"soundcloud"},
    SCRIBD: {domObj:"IFRAME",compare:{attr:"src",value:"scribd.com/embeds"}, blockName:"scribd"},
    DATAFACTORY: {domObj:"IFRAME",compare:{attr:"src",value:"https://mam.tn.com.ar/html/v3/"}, blockName:"datafactory"},
    WAZE: {domObj:"IFRAME",compare:{attr:"src",value:"https://embed.waze.com"}, blockName:"waze"},
    RADIOCUT: {domObj:"IFRAME",compare:{attr:"src",value:"radiocut.fm/audiocut/embed"}, blockName:"radiocut"},
    INFOGRAM: {domObj:"DIV",compare:{attr:"class",value:"infogram-embed"}, blockName:"infogram"},
    IMGUR: {domObj:"BLOCKQUOTE",compare:{attr:"class",value:"imgur-embed-pub"}, blockName:"imgur"},
    VIMEO: {domObj:"IFRAME",compare:{attr:"src",value:"player.vimeo.com/video"}, blockName:"vimeo"},
    TIMELINE: {domObj:"IFRAME",compare:{attr:"src",value:"cdn.knightlab.com"}, blockName:"timeline"},
    CLARINVIDEO: {domObj:"IFRAME",compare:{attr:"src",value:"vodgc.com/p"}, blockName:"clarinvideo"},
    MIXCLOUD: {domObj:"IFRAME",compare:{attr:"src",value:"mixcloud.com/widget/iframe/"}, blockName:"mixcloud"},
    THINGLINKSIMG: {domObj:"IFRAME",compare:{attr:"src",value:"www.thinglink.com/card/"}, blockName:"thinglink"},
    RICOHTHETA: {domObj:"BLOCKQUOTE",compare:{attr:"class",value:"ricoh-theta-spherical-image"}, blockName:"ricohtheta"},
    GIPKY: { domObj: "IFRAME", compare: { attr: "src", value: "giphy.com/embed/" }, blockName: "giphy" },
    PREZI: { domObj: "IFRAME", compare: { attr: "src", value: "prezi.com/embed/" }, blockName: "prezi" },
    PLAYBUZZ: { domObj: "DIV", compare: { attr: "class", value: "pb_feed" }, blockName: "playbuzz" }
};
